Repository MadhavKrishanGoswami/InkCode-Fusion, pull requests merged in 2024-10, with the labels that each got.

#30 Improved Form Ui
  apps/web/public/index.html
  apps/web/src/components/Forms/createRoomForm/CreateRoomForm.jsx
  apps/web/src/components/Forms/index.jsx
  apps/web/src/components/Forms/joinRoomForm/JoinRoomForm.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#32 #Add Github Greetings.yml
  .github/workflows/Greetings.yml
Labels: gssoc-ext, level 1

#33 Create contributing.md file
  CONTRIBUTING.md
Labels: gssoc-ext

#40 Create auto-comment-on-close.yml
  .github/workflows/auto-comment-on-close.yml
Labels: gssoc-ext
